-- DEPRECATED: this file is intentionally not an executable schema.
--
-- The canonical FieldCraft database definition is the ordered migration chain:
--   migrations/202608030001_fieldcraft_core.sql
--   migrations/202608030002_fieldcraft_functions.sql
--
-- Use `supabase db reset` to apply migrations locally. CI must never execute this
-- legacy path as a standalone schema source.
