import type { Job, Client, Expense, Invoice, InventoryItem } from '../types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

export const SEED_CLIENTS: Client[] = [
  {
    id: 'client-martinez',
    name: 'Rosa Martinez',
    phone: '(619) 555-0142',
    email: 'rosa.martinez@gmail.com',
    address: '4821 Sunridge Dr',
    city: 'Chula Vista',
    state: 'CA',
    zip: '91911',
    createdAt: daysAgo(45),
  },
  {
    id: 'client-thornton',
    name: 'Derek Thornton',
    phone: '(858) 555-0278',
    email: 'derek.thornton@outlook.com',
    address: '1205 Crestview Ln',
    city: 'El Cajon',
    state: 'CA',
    zip: '92021',
    createdAt: daysAgo(60),
  },
  {
    id: 'client-riverside',
    name: 'Riverside Commercial LLC',
    phone: '(619) 555-0391',
    email: 'ops@riversidecommercial.com',
    address: '8800 Riverside Blvd, Suite 200',
    city: 'San Diego',
    state: 'CA',
    zip: '92121',
    createdAt: daysAgo(90),
  },
]

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    jobId: 'job-martinez',
    number: 'FC-001',
    lineItems: [
      { id: 'li-1', description: 'Labor — Pipe repair & replacement', quantity: 2.5, unitPrice: 95, total: 237.50, type: 'labor' },
      { id: 'li-2', description: 'SharkBite 1/2" push-to-connect coupling (x3)', quantity: 3, unitPrice: 12.50, total: 37.50, type: 'material' },
      { id: 'li-3', description: 'PEX-A pipe 1/2" (10 ft)', quantity: 1, unitPrice: 22, total: 22, type: 'material' },
      { id: 'li-4', description: 'Teflon tape, pipe putty, misc fittings', quantity: 1, unitPrice: 14, total: 14, type: 'material' },
      { id: 'li-5', description: 'Service call / diagnostic', quantity: 1, unitPrice: 75, total: 75, type: 'labor' },
    ],
    subtotal: 386,
    taxRate: 0,
    taxAmount: 0,
    total: 386,
    paymentStatus: 'Sent',
    sentAt: daysAgo(2),
    paymentTerms: 'Net 14',
    createdAt: daysAgo(2),
    notes: 'Repaired supply line leak under kitchen sink and replaced corroded section of 1/2" pipe.',
  },
  {
    id: 'inv-002',
    jobId: 'job-riverside',
    number: 'FC-002',
    lineItems: [
      { id: 'li-6', description: 'Labor — Panel upgrade & installation', quantity: 8, unitPrice: 110, total: 880, type: 'labor' },
      { id: 'li-7', description: 'Square D 200A Main Breaker Panel (QO130L200PG)', quantity: 1, unitPrice: 485, total: 485, type: 'material' },
      { id: 'li-8', description: 'Square D 20A single-pole breakers (x8)', quantity: 8, unitPrice: 18, total: 144, type: 'material' },
      { id: 'li-9', description: 'Square D 30A double-pole breakers (x4)', quantity: 4, unitPrice: 28, total: 112, type: 'material' },
      { id: 'li-10', description: 'Ground rods, clamps, and bonding wire', quantity: 1, unitPrice: 95, total: 95, type: 'material' },
      { id: 'li-11', description: '6/3 aluminum service entrance cable (20 ft)', quantity: 1, unitPrice: 78, total: 78, type: 'material' },
      { id: 'li-12', description: 'Permit filing fee', quantity: 1, unitPrice: 185, total: 185, type: 'material' },
    ],
    subtotal: 1979,
    taxRate: 0.0875,
    taxAmount: 173.16,
    total: 2152.16,
    paymentStatus: 'Draft',
    paymentTerms: 'Net 30',
    createdAt: daysAgo(0),
    notes: 'Full 200A panel upgrade from 100A Federal Pacific. Permit required — filed with city.',
  },
  {
    id: 'inv-003',
    jobId: 'job-thornton',
    number: 'FC-003',
    lineItems: [
      { id: 'li-13', description: 'Labor — AC installation & commissioning', quantity: 6, unitPrice: 105, total: 630, type: 'labor' },
      { id: 'li-14', description: 'Carrier 3-ton 16 SEER central AC unit (24ACC636A003)', quantity: 1, unitPrice: 1480, total: 1480, type: 'material' },
      { id: 'li-15', description: 'Carrier air handler / evaporator coil', quantity: 1, unitPrice: 620, total: 620, type: 'material' },
      { id: 'li-16', description: 'Refrigerant R-410A (lbs)', quantity: 8, unitPrice: 22, total: 176, type: 'material' },
      { id: 'li-17', description: 'Copper line set 3/8" x 3/4" (25 ft)', quantity: 1, unitPrice: 145, total: 145, type: 'material' },
      { id: 'li-18', description: 'Condensate drain line & fittings', quantity: 1, unitPrice: 38, total: 38, type: 'material' },
      { id: 'li-19', description: 'Disconnect box & whip', quantity: 1, unitPrice: 65, total: 65, type: 'material' },
    ],
    subtotal: 3154,
    taxRate: 0.0875,
    taxAmount: 275.98,
    total: 3429.98,
    paymentStatus: 'Paid',
    sentAt: daysAgo(9),
    paidAt: daysAgo(7),
    paymentTerms: 'Due on receipt',
    createdAt: daysAgo(9),
    notes: '3-ton Carrier central AC replacement. Old unit disposed of. Tested and commissioned.',
  },
]

export const SEED_JOBS: Job[] = [
  {
    id: 'job-martinez',
    clientId: 'client-martinez',
    clientName: 'Rosa Martinez',
    title: 'Leaky pipe repair — Martinez Residence',
    tradeType: 'Plumbing',
    status: 'Invoiced',
    description: 'Diagnosed and repaired a supply line leak under the kitchen sink. Replaced corroded 1/2" pipe section with PEX-A and SharkBite fittings. Ran new section approximately 4 feet. Tested for leaks, all clear.',
    address: '4821 Sunridge Dr, Chula Vista, CA 91911',
    laborHours: 2.5,
    laborRate: 95,
    invoiceId: 'inv-001',
    invoiceTotal: 386,
    expenseIds: ['exp-001', 'exp-002'],
    notes: 'Rosa mentioned the water pressure seems low throughout the house — could be worth quoting a pressure regulator replacement on next visit.',
    scheduledAt: daysAgo(3),
    completedAt: daysAgo(2),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'job-riverside',
    clientId: 'client-riverside',
    clientName: 'Riverside Commercial LLC',
    title: 'Panel upgrade — Riverside Commercial',
    tradeType: 'Electrical',
    status: 'In Progress',
    description: 'Upgrading outdated 100A Federal Pacific panel to 200A Square D. Panel is in utility closet on ground floor. Will need to coordinate with PG&E for meter pull. Permit filed. Second day of work today.',
    address: '8800 Riverside Blvd, Suite 200, San Diego, CA 92121',
    laborHours: 8,
    laborRate: 110,
    invoiceId: 'inv-002',
    invoiceTotal: 2152.16,
    expenseIds: ['exp-003'],
    notes: 'PG&E meter pull scheduled for tomorrow morning 8–10am. Coordinate with building super (Mike, ext 204).',
    scheduledAt: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: 'job-thornton',
    clientId: 'client-thornton',
    clientName: 'Derek Thornton',
    title: 'AC unit install — Thornton Residence',
    tradeType: 'HVAC',
    status: 'Paid',
    description: 'Full replacement of existing 2.5-ton AC with new Carrier 3-ton 16 SEER unit. Upgraded to match new heat pump air handler installed last season. Pressure tested, evacuated to 500 microns, charged with R-410A.',
    address: '1205 Crestview Ln, El Cajon, CA 92021',
    laborHours: 6,
    laborRate: 105,
    invoiceId: 'inv-003',
    invoiceTotal: 3429.98,
    expenseIds: ['exp-004'],
    notes: 'Derek was very happy. Asked about adding a smart thermostat next time. Left a 5-star review.',
    scheduledAt: daysAgo(10),
    completedAt: daysAgo(9),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(7),
  },
]

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    jobId: 'job-martinez',
    clientId: 'client-martinez',
    vendor: 'Home Depot #4211',
    category: 'Materials',
    amount: 73.50,
    date: daysAgo(3),
    notes: 'PEX-A pipe, SharkBite fittings, Teflon tape, misc fittings for Martinez pipe repair',
    createdAt: daysAgo(3),
  },
  {
    id: 'exp-002',
    jobId: 'job-martinez',
    clientId: 'client-martinez',
    vendor: 'Chevron — Otay Ranch',
    category: 'Fuel',
    amount: 68.40,
    date: daysAgo(3),
    notes: 'Fuel — weekly fill-up, partial to Martinez job',
    createdAt: daysAgo(3),
  },
  {
    id: 'exp-003',
    jobId: 'job-riverside',
    clientId: 'client-riverside',
    vendor: 'Platt Electric Supply',
    category: 'Materials',
    amount: 914,
    date: daysAgo(1),
    notes: 'Square D 200A panel, breakers, service entrance cable — Riverside panel upgrade',
    createdAt: daysAgo(1),
  },
  {
    id: 'exp-004',
    jobId: 'job-thornton',
    clientId: 'client-thornton',
    vendor: 'Ferguson HVAC Supply',
    category: 'Materials',
    amount: 2304,
    date: daysAgo(10),
    notes: 'Carrier AC unit, evaporator coil, line set, refrigerant, disconnect box — Thornton AC install',
    createdAt: daysAgo(10),
  },
]

export const SEED_INVENTORY: InventoryItem[] = [
  { id: 'inv-item-1', name: '1/2" SharkBite couplings', quantity: 8, unit: 'ea', minStock: 5 },
  { id: 'inv-item-2', name: '3/4" PEX-A pipe', quantity: 25, unit: 'ft', minStock: 10 },
  { id: 'inv-item-3', name: '20A single-pole breakers', quantity: 4, unit: 'ea', minStock: 3 },
  { id: 'inv-item-4', name: 'Wire nuts (assorted)', quantity: 1, unit: 'box', minStock: 1 },
  { id: 'inv-item-5', name: 'Teflon tape', quantity: 3, unit: 'rolls', minStock: 2 },
  { id: 'inv-item-6', name: 'R-410A refrigerant', quantity: 20, unit: 'lbs', minStock: 10 },
  { id: 'inv-item-7', name: '12/2 Romex (NM-B)', quantity: 50, unit: 'ft', minStock: 25 },
  { id: 'inv-item-8', name: 'Condensate drain line 3/4"', quantity: 15, unit: 'ft', minStock: 5 },
]

export const SEED_USER = {
  name: 'Mike Callahan',
  businessName: 'Callahan Trade Services',
  tradeType: 'Plumbing' as const,
  hourlyRate: 95,
  phone: '(619) 555-0199',
  email: 'mike@callahantrades.com',
  address: '1402 Market St, San Diego, CA 92101',
  taxRate: 0.0875,
  licenseNumber: 'C-36 #892341',
  onboardingComplete: true,
}
